apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-jwt-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.jwt.secret | quote }}
